name: Backend Unit Test

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend-test.yml"

jobs:
  phpunit:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer

      - name: Show PHP version
        run: php -v

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPUnit
        run: composer test
