DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id CHAR(255) NOT NULL PRIMARY KEY DEFAULT (UUID()),
    name VARCHAR(100),
    email VARCHAR(255),
    google_id VARCHAR(255) UNIQUE,
    avatar_url VARCHAR(512),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
